services:
  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
    container_name: dqlabs_web
    restart: always
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    networks:
      - dqlabs_network

networks:
  dqlabs_network:
    external: true
